### PR TITLE
Pytorch support added

### PR DESCRIPTION
**Pull request by lzw365-code**
Pytorch support added, the pytorch model can be integrated by the model_torch script. It supports both TensorFlow and pytorch

### CODE REVIEW

**Comment by dongheuw** [comment]
Could you make the support for both pytorch and tensorflow models within the same api and encapsulate it in a single class?

**Comment by lzw365-code** [comment]
Sure, just wonder how should I let the user choose which model they pass
in? For example should I let user pass in an extra parameter saying which
model they use, or I should I auto detect which model is passed in?

**Comment by dongheuw** [comment]
user could pass in 'torch' or 'tensorflow' to specify, or 'infer' to let the system determine. probably create a class and encapsulate all these methods and use class variables for such metadata. Some API might change though.

**Comment by lzw365-code** [comment]
Sure, will fix it soon

**Comment by lzw365-code** [comment]
will create a new merge request

**Pull request closed without merging**
